resolver: lts-12.19
packages:
  - .
extra-deps:
#  - dhall-1.18.0@rev:0
  - github: dhall-lang/dhall-haskell
    commit: b7e5a0ddd19213bbacba47ded294660c2401c87e
    subdirs:
      - dhall
  - Cabal-2.4.0.0@rev:0
  - megaparsec-7.0.1
  - repline-0.2.0.0
  - serialise-0.2.1.0
allow-newer: true
