-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
< AArch64
| Alpha
| Arm
| Hppa
| I386
| IA64
| JavaScript
| M68k
| Mips
| OtherArch :
    { _1 : Text }
| PPC
| PPC64
| Rs6000
| S390
| SH
| Sparc
| Vax
| X86_64
>
