-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
{ Eta :
    List Text
, GHC :
    List Text
, GHCJS :
    List Text
, HBC :
    List Text
, Helium :
    List Text
, Hugs :
    List Text
, JHC :
    List Text
, LHC :
    List Text
, NHC :
    List Text
, UHC :
    List Text
, YHC :
    List Text
}
