-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
< Eta
| GHC
| GHCJS
| HBC
| HaskellSuite :
    { _1 : Text }
| Helium
| Hugs
| JHC
| LHC
| NHC
| OtherCompiler :
    { _1 : Text }
| UHC
| YHC
>
