-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
{ arch :
    ./Arch.dhall → Bool
, flag :
    Text → Bool
, impl :
    ./Compiler.dhall → ./VersionRange.dhall → Bool
, os :
    ./OS.dhall → Bool
}
