-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
  ./BuildInfo.dhall
⩓ { type :
      ./ForeignLibType.dhall
  , options :
      List ./ForeignLibOption.dhall
  , lib-version-info :
      Optional { current : Natural, revision : Natural, age : Natural }
  , lib-version-linux :
      Optional ./Version.dhall
  , mod-def-files :
      List Text
  }
