-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
  ./BuildInfo.dhall
⩓ { exposed-modules :
      List Text
  , reexported-modules :
      List { original : { package : Optional Text, name : Text }, name : Text }
  , signatures :
      List Text
  }
