-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
< AGPL :
    Optional ./Version.dhall
| AllRightsReserved
| Apache :
    Optional ./Version.dhall
| BSD2
| BSD3
| BSD4
| GPL :
    Optional ./Version.dhall
| ISC
| LGPL :
    Optional ./Version.dhall
| MIT
| MPL :
    ./Version.dhall
| Other
| PublicDomain
| SPDX :
    ./SPDX.dhall
| Unknown :
    Text
| Unspecified
>
