-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
< default | hiding : List Text | renaming : List { rename : Text, to : Text } >
