-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
< AIX
| Android
| DragonFly
| FreeBSD
| Ghcjs
| HPUX
| HaLVM
| Hurd
| IOS
| IRIX
| Linux
| NetBSD
| OSX
| OpenBSD
| OtherOS :
    { _1 : Text }
| Solaris
| Windows
>
