-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
< Bazaar
| CVS
| Darcs
| Git
| GnuArch
| Mercurial
| Monotone
| OtherRepoType :
    { _1 : Text }
| SVN
>
