-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
{ branch :
    Optional Text
, kind :
    ./RepoKind.dhall
, location :
    Optional Text
, module :
    Optional Text
, subdir :
    Optional Text
, tag :
    Optional Text
, type :
    Optional ./RepoType.dhall
}
