-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
  ./BuildInfo.dhall
⩓ { type :
      < exitcode-stdio : { main-is : Text } | detailed : { module : Text } >
  }
