-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
let types = ../types.dhall

in  { type =
        None types.RepoType
    , location =
        None Text
    , module =
        None Text
    , branch =
        None Text
    , tag =
        None Text
    , subdir =
        None Text
    , kind =
        types.RepoKind.RepoHead
    }
