-- This file is auto-generated by dhall-to-cabal-meta. Look but don't touch (unless you want your edits to be over-written).
    let types = ./../types.dhall

in  { type =
        [] : Optional types.RepoType
    , location =
        [] : Optional Text
    , module =
        [] : Optional Text
    , branch =
        [] : Optional Text
    , tag =
        [] : Optional Text
    , subdir =
        [] : Optional Text
    , kind =
        (constructors types.RepoKind).RepoHead {=}
    }